version: '3.3'
services:
  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", ""]
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"