spring:
  application:
    name: ms-auth

  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: heybetmovlamov2005@gmail.com
    password: shqj qdts kxkw lngf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 3000
          timeout: 3000
          writetimeout: 3000

application:
  client:
    ms-user:
      url: http://localhost:8080
  cache:
    email-otp:
      prefix: "email_otp"
      ttl: 300

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
