spring:
  application:
    name: ms-auth

  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

application:
  client:
    ms-user:
      url: http://localhost:8080
  cache:
    email-otp:
      prefix: "email_otp"
      ttl: 300

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
